/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author Evita Alice Paul
 */
public class ViewBrokers extends javax.swing.JPanel {

    /**
     * Creates new form ViewBrokers
     */
    public ViewBrokers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbrokers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbbrokerfee = new javax.swing.JComboBox<>();
        btnsearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(620, 240, 72, 23);

        tblbrokers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "License Number", "Name", "Contact Number", "Broker Fee"
            }
        ));
        jScrollPane1.setViewportView(tblbrokers);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 690, 126);

        jLabel1.setText("Broker Fee :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 240, 70, 20);

        cmbbrokerfee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "< 1000", "1000 - 2000", "2000 - 3000", "3000 - 4000", "> 4000" }));
        jPanel1.add(cmbbrokerfee);
        cmbbrokerfee.setBounds(380, 240, 93, 22);

        btnsearch.setText("Search");
        jPanel1.add(btnsearch);
        btnsearch.setBounds(490, 240, 72, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pritika\\Downloads\\broker2.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 200, 670, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cmbbrokerfee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbrokers;
    // End of variables declaration//GEN-END:variables
}
