/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Broker;
import javax.swing.JOptionPane;
import Model.BrokerDirectory;
import Model.SQLconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pritika
 */
public class AddBroker extends javax.swing.JPanel {

    /**
     * Creates new form AddBroker
     */
    int b ;
    BrokerDirectory bd = new BrokerDirectory();
    ArrayList<Broker > blist;
    
  DefaultTableModel model;
    public AddBroker() {
        initComponents();
        bd=new BrokerDirectory();
        this.b = b;
        //this.blist = bd;
        //String Query;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbrokername = new javax.swing.JLabel();
        lbllicenseno = new javax.swing.JLabel();
        lblcontactno = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblbrokerfee = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblmanagement = new javax.swing.JLabel();
        txtbrokername = new javax.swing.JTextField();
        txtlicenseno = new javax.swing.JTextField();
        txtcontactno = new javax.swing.JTextField();
        txtemailid = new javax.swing.JTextField();
        txtbrokerfee = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtmanagement = new javax.swing.JTextField();
        btnaddbroker = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblbrokername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblbrokername.setText("Broker Name:");

        lbllicenseno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllicenseno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbllicenseno.setText("License No:");

        lblcontactno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcontactno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcontactno.setText("Contact No:");

        lblemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblemail.setText("Email ID:");

        lblbrokerfee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblbrokerfee.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblbrokerfee.setText("Broker Fee:");

        lblusername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusername.setText("Username:");
        lblusername.setFocusTraversalPolicyProvider(true);

        lblpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpassword.setText("Password:");

        lblmanagement.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblmanagement.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmanagement.setText("Management:");

        txtbrokername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbrokernameActionPerformed(evt);
            }
        });

        btnaddbroker.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnaddbroker.setText("Add Broker");
        btnaddbroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbrokerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblbrokername, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(lbllicenseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcontactno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblbrokerfee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtusername)
                    .addComponent(txtbrokerfee)
                    .addComponent(txtemailid)
                    .addComponent(txtcontactno)
                    .addComponent(txtlicenseno)
                    .addComponent(txtbrokername)
                    .addComponent(txtmanagement))
                .addGap(65, 65, 65)
                .addComponent(btnaddbroker)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbrokername)
                    .addComponent(txtbrokername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllicenseno)
                    .addComponent(txtlicenseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontactno)
                    .addComponent(txtcontactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(txtemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbrokerfee)
                    .addComponent(txtbrokerfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanagement)
                    .addComponent(txtmanagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddbroker))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtbrokernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrokernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrokernameActionPerformed

    private void btnaddbrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbrokerActionPerformed
        // TODO add your handling code here:
        
        String brokername = txtbrokername.getText();
        String Licenseno = txtlicenseno.getText();
        String contact = txtcontactno.getText();
        String email = txtemailid.getText();
        String brokerfee = txtbrokerfee.getText();
        String username = txtusername.getText();
        String password = txtpassword.getText();
        String management = txtmanagement.getText();
        
        if(brokername.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Broker Name");
        }else if(Licenseno.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the License Number");
        }else if(contact.isBlank()){
             JOptionPane.showMessageDialog(this,"Please enter the Contact Number");
        }else if(email.isBlank()){
               JOptionPane.showMessageDialog(this,"Please enter the Email ID");
        }else if(brokerfee.isBlank()){
             JOptionPane.showMessageDialog(this,"Please enter the Broker Fee");
        }else if(username.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Username");
        }else if(password.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Password");
        }else if(management.isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the Management");
        }else{
            //JOptionPane.showMessageDialog(this,"Registeration Successfull");
        
        System.out.println("Before try statement executed");
       
        try {
            System.out.println("Inside try statement executed");
              Connection con=SQLconnection.dbconnector();
            Statement stmt=con.createStatement();
            
          String Query= "INSERT INTO Brokers(name,licenseno,contactno,emailid,brokerfee,USERNAME,PASSWORD,management) values('"+txtbrokername.getText()+"','"+txtlicenseno.getText()+"','"+txtcontactno.getText()+"','"+txtemailid.getText()+"','"+txtbrokerfee.getText()+"','"+txtusername.getText()+"','"+txtpassword.getText()+"','"+txtmanagement.getText()+"')";
          
         
            stmt.executeUpdate(Query);
          stmt.close();
          con.close();
            JOptionPane.showMessageDialog(this, "Registered Sucessfully");
       
            
        
       
        } catch (SQLException ex) {
            Logger.getLogger(AddBroker.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
    }//GEN-LAST:event_btnaddbrokerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddbroker;
    private javax.swing.JLabel lblbrokerfee;
    private javax.swing.JLabel lblbrokername;
    private javax.swing.JLabel lblcontactno;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lbllicenseno;
    private javax.swing.JLabel lblmanagement;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtbrokerfee;
    private javax.swing.JTextField txtbrokername;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtlicenseno;
    private javax.swing.JTextField txtmanagement;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
