/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Apartmentlistings;
import Model.Broker;
import Model.Market;
import Model.Requeststudent;
import Model.SQLconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Model.Markethistory;
import Model.Market;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pritika
 */
public class MarketplaceAddproducts extends javax.swing.JPanel {

    /**
     * Creates new form MarketplaceAddproducts
     */
   
    
    Markethistory mh= new Markethistory();
    Market mp;
    public MarketplaceAddproducts() {
        initComponents();
        mh.getMarketHistory();
        this.mp = mp;
        PopulateTable();
           
          
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmarketplace = new javax.swing.JTable();
        btndelete = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(0, 153, 153));
        setFocusTraversalPolicyProvider(true);
        setName(""); // NOI18N

        tblmarketplace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Price", "Used / Unused", "Image"
            }
        ));
        jScrollPane1.setViewportView(tblmarketplace);

        btndelete.setText("REMOVE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndelete)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btndelete)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblmarketplace.getSelectedRow();
         try {
           DefaultTableModel model =(DefaultTableModel) tblmarketplace.getModel();
               Market mp = (Market)model.getValueAt(selectedRowIndex,4);
               mh.deleteMarket(mp);
           // System.out.println("Inside try statement executed");
            // JOptionPane.showMessageDialog(this, "Record deleted Successfully");
              Connection con=SQLconnection.dbconnector();
              Statement stmt =  con.createStatement();
              
           String idea;
            idea= (String) model.getValueAt(selectedRowIndex,0);
           String query = "delete from Product where Name='"+idea+"' ";
            stmt.executeUpdate(query);
            stmt.close();
         
            PopulateTable();
            JOptionPane.showMessageDialog(this, "Deleted Successfully");
              } catch (SQLException ex) {
                Logger.getLogger(DisplayBrokers.class.getName()).log(Level.SEVERE, null, ex);
            }      
           
        
    }//GEN-LAST:event_btndeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmarketplace;
    // End of variables declaration//GEN-END:variables
private void PopulateTable() {
        
        DefaultTableModel model= (DefaultTableModel) tblmarketplace.getModel();
        model.setRowCount(0);
        
        for (Market mp : mh.getList()){
        
        Object[] row = new Object[5];
            row[0] = mp.getName();
            row[1] = mp.getPrice();
            row[2] = mp.getUsed();
            
            row[3] = mp;
           
            model.addRow(row);
        }
        
        }
}
