/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Evita Alice Paul
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
          this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnstudent = new javax.swing.JButton();
        btnuniversity = new javax.swing.JButton();
        btnheadrealtor = new javax.swing.JButton();
        btnbroker = new javax.swing.JButton();
        btnlandlord = new javax.swing.JButton();
        btnmarketplaceadmin = new javax.swing.JButton();
        btntechsupport = new javax.swing.JButton();
        btnsysadmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("STUDENT HOUSING DATABASE MANAGEMENT SYSTEM");

        btnstudent.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnstudent.setText("Student ");
        btnstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentActionPerformed(evt);
            }
        });

        btnuniversity.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnuniversity.setText("University Admin");
        btnuniversity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuniversityActionPerformed(evt);
            }
        });

        btnheadrealtor.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnheadrealtor.setText("Head Realtor");
        btnheadrealtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnheadrealtorActionPerformed(evt);
            }
        });

        btnbroker.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnbroker.setText("Broker");
        btnbroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrokerActionPerformed(evt);
            }
        });

        btnlandlord.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnlandlord.setText("Landlord");
        btnlandlord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlandlordActionPerformed(evt);
            }
        });

        btnmarketplaceadmin.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnmarketplaceadmin.setText("Marketplace Admin");
        btnmarketplaceadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarketplaceadminActionPerformed(evt);
            }
        });

        btntechsupport.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btntechsupport.setText("Tech Support");
        btntechsupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntechsupportActionPerformed(evt);
            }
        });

        btnsysadmin.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnsysadmin.setText("System Admin");
        btnsysadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsysadminActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apartmentbuilding.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnmarketplaceadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntechsupport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlandlord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnheadrealtor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnuniversity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsysadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnstudent)
                        .addGap(28, 28, 28)
                        .addComponent(btnuniversity)
                        .addGap(29, 29, 29)
                        .addComponent(btnheadrealtor)
                        .addGap(29, 29, 29)
                        .addComponent(btnbroker)
                        .addGap(30, 30, 30)
                        .addComponent(btnlandlord)
                        .addGap(30, 30, 30)
                        .addComponent(btnmarketplaceadmin)
                        .addGap(29, 29, 29)
                        .addComponent(btntechsupport)
                        .addGap(28, 28, 28)
                        .addComponent(btnsysadmin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsysadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsysadminActionPerformed
        // TODO add your handling code here:
         SystemadminLoginpage frame=new SystemadminLoginpage();
                frame.setTitle("System Admin");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
        
    }//GEN-LAST:event_btnsysadminActionPerformed

    private void btnuniversityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuniversityActionPerformed
        // TODO add your handling code here:
       UniversityadminLoginpage frame=new UniversityadminLoginpage();
                frame.setTitle("University");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnuniversityActionPerformed

    private void btnstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentActionPerformed
        // TODO add your handling code here:
        LogonPage frame=new LogonPage();
                frame.setTitle("Student");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnstudentActionPerformed

    private void btnheadrealtorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnheadrealtorActionPerformed
        // TODO add your handling code here:
         HeadRealtorLoginpage frame=new HeadRealtorLoginpage();
                frame.setTitle("Head Realtor");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnheadrealtorActionPerformed

    private void btnbrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrokerActionPerformed
        // TODO add your handling code here:
        BrokerLoginpage frame=new BrokerLoginpage();
                frame.setTitle("Broker");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnbrokerActionPerformed

    private void btnlandlordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlandlordActionPerformed
        // TODO add your handling code here:
         LandlordLoginpage frame=new LandlordLoginpage();
                frame.setTitle("Landlord");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnlandlordActionPerformed

    private void btnmarketplaceadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarketplaceadminActionPerformed
        // TODO add your handling code here:
         MarketplaceadminLoginpage frame=new MarketplaceadminLoginpage ();
                frame.setTitle("Market Place");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btnmarketplaceadminActionPerformed

    private void btntechsupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntechsupportActionPerformed
        // TODO add your handling code here:
        TechsupportLoginpage frame=new TechsupportLoginpage ();
                frame.setTitle("Technical Support");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentView.EXIT_ON_CLOSE);
                frame.setResizable(false);
    }//GEN-LAST:event_btntechsupportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbroker;
    private javax.swing.JButton btnheadrealtor;
    private javax.swing.JButton btnlandlord;
    private javax.swing.JButton btnmarketplaceadmin;
    private javax.swing.JButton btnstudent;
    private javax.swing.JButton btnsysadmin;
    private javax.swing.JButton btntechsupport;
    private javax.swing.JButton btnuniversity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
