/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Marketrequeststudent;
import Model.Marketrequeststudenthistory;
import Model.Requeststudent;
import Model.Studenthistory;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Pritika
 */
public class ViewSaleRequests extends javax.swing.JPanel {

    /**
     * Creates new form ViewSaleRequests
     */
    Marketrequeststudenthistory h = new  Marketrequeststudenthistory();
    public ViewSaleRequests() {
        initComponents();
        h.getMarketrequeststudentHistory();
        PopulateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblviewstudent = new javax.swing.JTable();
        btnpdf = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setAutoscrolls(true);

        tblviewstudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact Number", "Email", "null"
            }
        ));
        jScrollPane1.setViewportView(tblviewstudent);
        if (tblviewstudent.getColumnModel().getColumnCount() > 0) {
            tblviewstudent.getColumnModel().getColumn(4).setMinWidth(0);
            tblviewstudent.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblviewstudent.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        btnpdf.setText("Generate PDF");
        btnpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnpdf)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(btnpdf)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpdfActionPerformed
        // TODO add your handling code here:
         String path="";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x=j.showSaveDialog(this);
        
        if(x==JFileChooser.APPROVE_OPTION)
        {
            path=j.getSelectedFile().getPath();
            
        }
        
        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"TourRequestAcceptance.pdf"));
            
            doc.open();
            
            PdfPTable tb1 = new PdfPTable(4);
            
      //      PdfPTable tb2 = new PdfPTable(3);
         
    //     System.out.println("The Bill\n");
         
           
            tb1.addCell("Name");
            tb1.addCell("Id");
            tb1.addCell("ContactNumber");
            tb1.addCell("EmailId");
            
            


            for(int i=0;i<tblviewstudent.getRowCount();i++)
            {
                String Name=tblviewstudent.getValueAt(i,1).toString();
                 String ID=tblviewstudent.getValueAt(i,0).toString();
                  String ContactNumber=tblviewstudent.getValueAt(i,2).toString();
                   String EmailId=tblviewstudent.getValueAt(i,3).toString();
                
               
                
                tb1.addCell(Name);
                tb1.addCell(ID);
                tb1.addCell(ContactNumber);
                tb1.addCell(EmailId);
               
                
            }
            doc.add(tb1);
                    
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewHouseTourrequests.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ViewHouseTourrequests.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        doc.close();
        JOptionPane.showMessageDialog(this,"Sale Processed");
    }//GEN-LAST:event_btnpdfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpdf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblviewstudent;
    // End of variables declaration//GEN-END:variables
private void PopulateTable() {
        
        DefaultTableModel model= (DefaultTableModel) tblviewstudent.getModel();
        model.setRowCount(0);
        
        for (Marketrequeststudent s : h.getHistory()){
        
        Object[] row = new Object[5];
            row[0] = s.getId();
            row[1] = s.getName();
            row[2] = s.getContactNumber();
            row[3] = s.getEmailId();
            row[4] = s;
           
            model.addRow(row);
        }
        
        }}
