/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Apartmentlistings;
import Model.ApartmentlistingsDirectory;
import Model.Broker;
import Model.SQLconnection;
import Model.Student;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Evita Alice Paul
 */
public class ViewApartmentlistings extends javax.swing.JPanel {

    /**
     * Creates new form ViewApartmentlistings
     */
    ApartmentlistingsDirectory ad= new ApartmentlistingsDirectory();
    ArrayList<Apartmentlistings > alist;
 
 
    public ViewApartmentlistings() {
        initComponents();
         
        ad.getApartmentlistingsDirectory();
        PopulateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        btnstudio = new javax.swing.JRadioButton();
        btnonebhk = new javax.swing.JRadioButton();
        btntwobhk = new javax.swing.JRadioButton();
        btnthreebhk = new javax.swing.JRadioButton();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblapartmentlistings = new javax.swing.JTable();
        lblapttype = new javax.swing.JLabel();
        txtapttype = new javax.swing.JTextField();
        lbllandname = new javax.swing.JLabel();
        txtlandname = new javax.swing.JTextField();
        lblprice = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        lblutilities = new javax.swing.JLabel();
        txtutilities = new javax.swing.JTextField();
        lblgrocery = new javax.swing.JLabel();
        txtgrocery = new javax.swing.JTextField();
        lblhospitals = new javax.swing.JLabel();
        txthospitals = new javax.swing.JTextField();
        lblmbta = new javax.swing.JLabel();
        txtmbta = new javax.swing.JTextField();
        lblbrokername = new javax.swing.JLabel();
        txtbrokername = new javax.swing.JTextField();
        lblemailid = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();
        lblaptname = new javax.swing.JLabel();
        txtaptname = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnview = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        lblphoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        buttonGroup.add(btnstudio);
        btnstudio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnstudio.setText("Studio");
        btnstudio.setContentAreaFilled(false);
        btnstudio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudioActionPerformed(evt);
            }
        });

        buttonGroup.add(btnonebhk);
        btnonebhk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnonebhk.setText("1 BHK");

        buttonGroup.add(btntwobhk);
        btntwobhk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntwobhk.setText("2 BHK");

        buttonGroup.add(btnthreebhk);
        btnthreebhk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthreebhk.setText("3 BHK");

        btnsearch.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        tblapartmentlistings.setBackground(new java.awt.Color(204, 255, 204));
        tblapartmentlistings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Apartment Type", "Landlord Name", "Price", "Utilities", "Grocery Stores", "Hospitals", "MBTA", "Broker Name", "Email ID", "Apartment Name", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblapartmentlistings.setShowGrid(false);
        tblapartmentlistings.setShowHorizontalLines(true);
        tblapartmentlistings.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblapartmentlistings);
        if (tblapartmentlistings.getColumnModel().getColumnCount() > 0) {
            tblapartmentlistings.getColumnModel().getColumn(3).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(3).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(4).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(4).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(5).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(5).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(6).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(6).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(8).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        lblapttype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblapttype.setText("Apartment Type :");

        txtapttype.setEditable(false);

        lbllandname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllandname.setText("Landlord Name :");

        txtlandname.setEditable(false);

        lblprice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblprice.setText("Price :");

        txtprice.setEditable(false);

        lblutilities.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblutilities.setText("Utilities :");

        txtutilities.setEditable(false);

        lblgrocery.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblgrocery.setText("Grocery Stores :");

        txtgrocery.setEditable(false);

        lblhospitals.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblhospitals.setText("Hospitals :");

        txthospitals.setEditable(false);

        lblmbta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblmbta.setText("MBTA :");

        txtmbta.setEditable(false);

        lblbrokername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblbrokername.setText("Broker name :");

        txtbrokername.setEditable(false);

        lblemailid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemailid.setText("Email ID :");

        txtemailid.setEditable(false);

        lblaptname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblaptname.setText("Apartment Name :");

        txtaptname.setEditable(false);

        lblid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblid.setText("ID :");

        txtid.setEditable(false);

        btnview.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btnrefresh.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        lblphoto.setText("Photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnonebhk)
                .addGap(64, 64, 64)
                .addComponent(btntwobhk)
                .addGap(70, 70, 70)
                .addComponent(btnthreebhk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblid)
                    .addComponent(lblaptname)
                    .addComponent(lblemailid)
                    .addComponent(lblbrokername)
                    .addComponent(lblhospitals)
                    .addComponent(lblgrocery)
                    .addComponent(lblutilities)
                    .addComponent(lblprice)
                    .addComponent(lbllandname)
                    .addComponent(lblapttype)
                    .addComponent(lblmbta))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlandname, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtid)
                    .addComponent(txtapttype)
                    .addComponent(txtprice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtutilities, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtgrocery, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txthospitals, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmbta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtbrokername, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtemailid)
                    .addComponent(txtaptname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnview)
                        .addGap(77, 77, 77)
                        .addComponent(btnrefresh))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstudio)
                    .addComponent(btnonebhk)
                    .addComponent(btntwobhk)
                    .addComponent(btnthreebhk)
                    .addComponent(btnsearch))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapttype)
                    .addComponent(txtapttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnview)
                    .addComponent(btnrefresh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllandname)
                            .addComponent(txtlandname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblutilities)
                            .addComponent(txtutilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgrocery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgrocery, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthospitals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmbta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmbta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblphoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbrokername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbrokername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblaptname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
       
         String studio= btnstudio.getText();
            String one = btnonebhk.getText();
            String two = btntwobhk.getText();
            String three = btnthreebhk.getText();

        DefaultTableModel model = (DefaultTableModel) tblapartmentlistings.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        tblapartmentlistings.setRowSorter(trs);
        if(btnstudio.isSelected()){
    trs.setRowFilter(RowFilter.regexFilter(studio));
               
        }else if(btnonebhk.isSelected()){
              trs.setRowFilter(RowFilter.regexFilter(one));
        }else if(btntwobhk.isSelected()){
             trs.setRowFilter(RowFilter.regexFilter(two));
        }else if(btnthreebhk.isSelected()){
             trs.setRowFilter(RowFilter.regexFilter(three));
        }else {
            JOptionPane.showMessageDialog(this, "Please select an Option");
        }
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudioActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_btnstudioActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
     
        
    
         int selectedRowIndex = tblapartmentlistings.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this,"Select a row to View");
            return;
        }
        DefaultTableModel model=(DefaultTableModel) tblapartmentlistings.getModel();
        //Broker SelectedBroker = (Broker) model.getValueAt(selectedRowIndex, 5);

        //txtlicenseno.setText(Integer.toString(SelectedBroker.getLicenseno()));
        //txtname.setText(String.valueOf(SelectedBroker.getName()));
        //txtcontactno.setText(String.valueOf(SelectedBroker.getContactno()));
        //txtbrokerfee.setText(Integer.toString(SelectedBroker.getBrokerfee()));
        //txtmanagement.setText(String.valueOf(SelectedBroker.getManagement()));
        // txtemail.setText(String.valueOf(SelectedBroker.getEmail()));
        txtaptname.setText(model.getValueAt(selectedRowIndex,9).toString());
        txtapttype.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtbrokername.setText(model.getValueAt(selectedRowIndex, 7).toString());
        txtemailid.setText(model.getValueAt(selectedRowIndex, 8).toString());
        txtgrocery.setText(model.getValueAt(selectedRowIndex, 4).toString());
        txthospitals.setText(model.getValueAt(selectedRowIndex, 5).toString());
        txtid.setText(model.getValueAt(selectedRowIndex, 10).toString());
        txtlandname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtmbta.setText(model.getValueAt(selectedRowIndex, 6).toString());
        txtprice.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtutilities.setText(model.getValueAt(selectedRowIndex, 3).toString());

      
        if(selectedRowIndex == 0){
        
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        

              
        }else if(selectedRowIndex == 1 ){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 2){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 3){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 4){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 5){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 6){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 7){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 8){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else if(selectedRowIndex == 9){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\students.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        }else{
             JOptionPane.showMessageDialog(this,"Error");
        }   
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
         
          txtaptname.setText("");
        txtapttype.setText("");
        txtbrokername.setText("");
        txtemailid.setText("");
        txtgrocery.setText("");
        txthospitals.setText("");
        txtid.setText("");
        txtlandname.setText("");
        txtmbta.setText("");
        txtprice.setText("");
        txtutilities.setText("");
        lblphoto.setIcon(null);
        buttonGroup.clearSelection();
       if( btnrefresh.isSelected()){
       PopulateTable();
       }else{
           
       }
    }//GEN-LAST:event_btnrefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnonebhk;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsearch;
    private javax.swing.JRadioButton btnstudio;
    private javax.swing.JRadioButton btnthreebhk;
    private javax.swing.JRadioButton btntwobhk;
    private javax.swing.JButton btnview;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblaptname;
    private javax.swing.JLabel lblapttype;
    private javax.swing.JLabel lblbrokername;
    private javax.swing.JLabel lblemailid;
    private javax.swing.JLabel lblgrocery;
    private javax.swing.JLabel lblhospitals;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbllandname;
    private javax.swing.JLabel lblmbta;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblutilities;
    private javax.swing.JTable tblapartmentlistings;
    private javax.swing.JTextField txtaptname;
    private javax.swing.JTextField txtapttype;
    private javax.swing.JTextField txtbrokername;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtgrocery;
    private javax.swing.JTextField txthospitals;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlandname;
    private javax.swing.JTextField txtmbta;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtutilities;
    // End of variables declaration//GEN-END:variables
private void PopulateTable()
    {
      
  
        DefaultTableModel model=(DefaultTableModel) tblapartmentlistings.getModel();
        model.setRowCount(0);
        for(Apartmentlistings a: ad.getList())
        {
             Object[] row=new Object[13];
             row[0]=a.getApartmenttype();
             
             row[1]=a.getLandlordname();
             row[2]=a.getPrice();
             row[3]=a.getUtilities();
             row[4]=a.getGrocerystores();
             row[5]=a.getHospital();
             row[6]=a.getMBTA();
             row[7]=a.getBrokerName();
             row[8]=a.getEmailID();
             row[9]=a.getApartmentname();
             row[10]= a.getID();
             row[11]=a;
             
    
             model.addRow(row);
        }  
    }
 public void search(String str,int i) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    System.out.println(str);
        DefaultTableModel model = (DefaultTableModel) tblapartmentlistings.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        tblapartmentlistings.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str,i));
        
    }
}
