/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import java.net.URL;
import Model.Apartmentlistings;
import Model.ApartmentlistingsDirectory;
import Model.Broker;
import Model.SQLconnection;
import Model.Student;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Evita Alice Paul
 */
public class ViewApartmentlistings extends javax.swing.JPanel {

    /**
     * Creates new form ViewApartmentlistings
     */
    ApartmentlistingsDirectory ad= new ApartmentlistingsDirectory();
   ArrayList<Apartmentlistings > alist;
 Apartmentlistings a;
 
    public ViewApartmentlistings() {
        initComponents();
         
        ad.getApartmentlistingsDirectory();
      this.a=a;
        System.out.println("Running");
        PopulateTable();
        //final JTextField url = new JTextField(20);
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        btnstudio = new javax.swing.JRadioButton();
        btnonebhk = new javax.swing.JRadioButton();
        btntwobhk = new javax.swing.JRadioButton();
        btnthreebhk = new javax.swing.JRadioButton();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblapartmentlistings = new javax.swing.JTable();
        lblapttype = new javax.swing.JLabel();
        txtapttype = new javax.swing.JTextField();
        lbllandname = new javax.swing.JLabel();
        txtlandname = new javax.swing.JTextField();
        lblprice = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        lblutilities = new javax.swing.JLabel();
        txtutilities = new javax.swing.JTextField();
        lblgrocery = new javax.swing.JLabel();
        txtgrocery = new javax.swing.JTextField();
        lblhospitals = new javax.swing.JLabel();
        txthospitals = new javax.swing.JTextField();
        lblmbta = new javax.swing.JLabel();
        txtmbta = new javax.swing.JTextField();
        lblbrokername = new javax.swing.JLabel();
        txtbrokername = new javax.swing.JTextField();
        lblemailid = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();
        lblaptname = new javax.swing.JLabel();
        txtaptname = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnview = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        lblphoto = new javax.swing.JLabel();
        btnlocation = new javax.swing.JButton();
        btnbooktour = new javax.swing.JButton();
        cmbtime = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));

        buttonGroup.add(btnstudio);
        btnstudio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnstudio.setText("Studio");
        btnstudio.setContentAreaFilled(false);
        btnstudio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudioActionPerformed(evt);
            }
        });

        buttonGroup.add(btnonebhk);
        btnonebhk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnonebhk.setText("1 BHK");

        buttonGroup.add(btntwobhk);
        btntwobhk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntwobhk.setText("2 BHK");

        buttonGroup.add(btnthreebhk);
        btnthreebhk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthreebhk.setText("3 BHK");

        btnsearch.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        tblapartmentlistings.setBackground(new java.awt.Color(204, 255, 204));
        tblapartmentlistings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Apartment Type", "Landlord Name", "Price", "Utilities", "Grocery Stores", "Hospitals", "MBTA", "Broker Name", "Email ID", "Apartment Name", "ID", "Title 12"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblapartmentlistings.setShowGrid(false);
        tblapartmentlistings.setShowHorizontalLines(true);
        tblapartmentlistings.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tblapartmentlistings);
        if (tblapartmentlistings.getColumnModel().getColumnCount() > 0) {
            tblapartmentlistings.getColumnModel().getColumn(3).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(3).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(4).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(4).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(5).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(5).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(6).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(6).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(6).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(8).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(8).setMaxWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(11).setMinWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(11).setPreferredWidth(0);
            tblapartmentlistings.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        lblapttype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblapttype.setText("Apartment Type :");

        txtapttype.setEditable(false);

        lbllandname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbllandname.setText("Landlord Name :");

        txtlandname.setEditable(false);

        lblprice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblprice.setText("Price :");

        txtprice.setEditable(false);

        lblutilities.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblutilities.setText("Utilities :");

        txtutilities.setEditable(false);

        lblgrocery.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblgrocery.setText("Grocery Stores :");

        txtgrocery.setEditable(false);

        lblhospitals.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblhospitals.setText("Hospitals :");

        txthospitals.setEditable(false);

        lblmbta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblmbta.setText("MBTA :");

        txtmbta.setEditable(false);

        lblbrokername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblbrokername.setText("Broker name :");

        txtbrokername.setEditable(false);

        lblemailid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemailid.setText("Email ID :");

        txtemailid.setEditable(false);

        lblaptname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblaptname.setText("Apartment Name :");

        txtaptname.setEditable(false);

        lblid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblid.setText("ID :");

        txtid.setEditable(false);

        btnview.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btnrefresh.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        lblphoto.setText("Photo");

        btnlocation.setText("Location");
        btnlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocationActionPerformed(evt);
            }
        });

        btnbooktour.setText("Book Apartment Tour");
        btnbooktour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbooktourActionPerformed(evt);
            }
        });

        cmbtime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "9 AM - 12 AM", "12 AM - 3 PM", "3 PM - 5 PM" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnonebhk)
                .addGap(64, 64, 64)
                .addComponent(btntwobhk)
                .addGap(70, 70, 70)
                .addComponent(btnthreebhk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblid)
                    .addComponent(lblaptname)
                    .addComponent(lblemailid)
                    .addComponent(lblbrokername)
                    .addComponent(lblhospitals)
                    .addComponent(lblgrocery)
                    .addComponent(lblutilities)
                    .addComponent(lblprice)
                    .addComponent(lbllandname)
                    .addComponent(lblapttype)
                    .addComponent(lblmbta))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtlandname, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(txtid)
                        .addComponent(txtapttype)
                        .addComponent(txtprice, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtutilities, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtgrocery, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txthospitals, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtmbta, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtbrokername, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtemailid)
                        .addComponent(txtaptname))
                    .addComponent(btnlocation))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbooktour)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnview)
                        .addGap(77, 77, 77)
                        .addComponent(btnrefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstudio)
                    .addComponent(btnonebhk)
                    .addComponent(btntwobhk)
                    .addComponent(btnthreebhk)
                    .addComponent(btnsearch))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapttype)
                    .addComponent(txtapttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnview)
                    .addComponent(btnrefresh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllandname)
                    .addComponent(txtlandname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblutilities)
                                    .addComponent(txtutilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtgrocery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblgrocery, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnbooktour)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhospitals, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthospitals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmbta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmbta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbrokername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblbrokername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblaptname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnlocation)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
       
         String studio= btnstudio.getText();
            String one = btnonebhk.getText();
            String two = btntwobhk.getText();
            String three = btnthreebhk.getText();

        DefaultTableModel model = (DefaultTableModel) tblapartmentlistings.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        tblapartmentlistings.setRowSorter(trs);
        if(btnstudio.isSelected()){
    trs.setRowFilter(RowFilter.regexFilter(studio));
               
        }else if(btnonebhk.isSelected()){
              trs.setRowFilter(RowFilter.regexFilter(one));
        }else if(btntwobhk.isSelected()){
             trs.setRowFilter(RowFilter.regexFilter(two));
        }else if(btnthreebhk.isSelected()){
             trs.setRowFilter(RowFilter.regexFilter(three));
        }else {
            JOptionPane.showMessageDialog(this, "Please select an Option");
        }
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudioActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_btnstudioActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
     
      
    
         int selectedRowIndex = tblapartmentlistings.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this,"Select a row to View");
            return;
        }
        DefaultTableModel model=(DefaultTableModel) tblapartmentlistings.getModel();
        //Broker SelectedBroker = (Broker) model.getValueAt(selectedRowIndex, 5);

        //txtlicenseno.setText(Integer.toString(SelectedBroker.getLicenseno()));
        //txtname.setText(String.valueOf(SelectedBroker.getName()));
        //txtcontactno.setText(String.valueOf(SelectedBroker.getContactno()));
        //txtbrokerfee.setText(Integer.toString(SelectedBroker.getBrokerfee()));
        //txtmanagement.setText(String.valueOf(SelectedBroker.getManagement()));
        // txtemail.setText(String.valueOf(SelectedBroker.getEmail()));
        txtaptname.setText(model.getValueAt(selectedRowIndex,9).toString());
        txtapttype.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txtbrokername.setText(model.getValueAt(selectedRowIndex, 7).toString());
        txtemailid.setText(model.getValueAt(selectedRowIndex, 8).toString());
        txtgrocery.setText(model.getValueAt(selectedRowIndex, 4).toString());
        txthospitals.setText(model.getValueAt(selectedRowIndex, 5).toString());
        txtid.setText(model.getValueAt(selectedRowIndex, 10).toString());
        txtlandname.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txtmbta.setText(model.getValueAt(selectedRowIndex, 6).toString());
        txtprice.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txtutilities.setText(model.getValueAt(selectedRowIndex, 3).toString());
        
   String apt= txtaptname.getText();
      
        if(apt.equals("JVUE")){
        
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\jvue.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
      

              
        }else if(apt.equals("Longwood") ){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\longwood.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("Mission Hill")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\missionhill.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("Mission Park")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\missionpark.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("West Square")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\westsquare.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("Parkway")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\parkway.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("Westland")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\westland.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("Vero")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\vero.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("Church Park")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\churchpark.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else if(apt.equals("Greenhouse")){
            
            ImageIcon icon = new ImageIcon("C:\\Users\\Evita Alice Paul\\OneDrive\\Documents\\NetBeansProjects\\StudentHousingApplication\\src\\Images\\greenhouse.jpg");

           Image image=icon.getImage().getScaledInstance(lblphoto.getWidth(),lblphoto.getHeight(),Image.SCALE_SMOOTH);
        
        lblphoto.setIcon(icon);
        
        }else{
             JOptionPane.showMessageDialog(this,"Error");
        }   
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
         
          txtaptname.setText("");
        txtapttype.setText("");
        txtbrokername.setText("");
        txtemailid.setText("");
        txtgrocery.setText("");
        txthospitals.setText("");
        txtid.setText("");
        txtlandname.setText("");
        txtmbta.setText("");
        txtprice.setText("");
        txtutilities.setText("");
        lblphoto.setIcon(null);
        buttonGroup.clearSelection();
       if( btnrefresh.isSelected()){
       PopulateTable();
       }else{
           
       }
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocationActionPerformed
        // TODO add your handling code here:
             // DefaultTableModel model = (DefaultTableModel) tblapartmentlistings.getModel();
         int selectedRowIndex = tblapartmentlistings.getSelectedRow();
           
          String apt= txtaptname.getText();
        try{
           if(apt.equals("JVUE") ){
               
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/J+Vue+at+the+LMA+Apartments/@42.3342965,-71.1030556,17z/data=!3m1!4b1!4m5!3m4!1s0x89e379890fad9993:0xd7f2c4e05f88e13c!8m2!3d42.3342893!4d-71.1008465").toURI());
           }else if(apt.equals("Longwood")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/The+Longwood/@42.3334423,-71.1038875,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37988dfd77cd7:0xdb25007468045253!8m2!3d42.3334497!4d-71.1016943?hl=en").toURI());
           }
           else if(apt.equals("Mission Hill")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Mission+Main+Apartments/@42.3339717,-71.100981,17z/data=!3m1!4b1!4m5!3m4!1s0x89e379899c9560a5:0x54a51bd35307f274!8m2!3d42.3339717!4d-71.0987923?hl=en").toURI());
           } 
             else if(apt.equals("Mission Park")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Mission+Park/@42.3336467,-71.1108708,17z/data=!3m1!4b1!4m5!3m4!1s0x89e379901ca1c0f1:0x501b2929438c510a!8m2!3d42.3336467!4d-71.1086821?hl=en").toURI());
           } 
           else if(apt.equals("West Square")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/West+Square+Apartments/@42.3409289,-71.0541777,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37a881852a5ff:0x73bc95f1c486ef23!8m2!3d42.340929!4d-71.049693?hl=en").toURI());
           } 
           else if(apt.equals("Parkway")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Parkway+Apartments/@42.2676322,-71.1714442,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37f2cf65b75fd:0x10a83257d368b63b!8m2!3d42.2676322!4d-71.1714442?hl=en").toURI());

        
           }  else if(apt.equals("Westland")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Westland+Avenue+Garage/@42.3438579,-71.0898203,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37a1a233fe3e3:0x13f6ebf4b208255e!8m2!3d42.3437529!4d-71.0876232?hl=en").toURI());
          
           }  else if(apt.equals("Vero")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Vero+Apartments/@42.3991368,-71.0440581,17z/data=!3m1!4b1!4m5!3m4!1s0x89e3713d5c02c3ed:0x57546e6acadd9554!8m2!3d42.3991368!4d-71.0418694?hl=en").toURI());
          
           }   else if(apt.equals("Church Park")){
               
                 Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Church+Park+Luxury+Apartments/@42.3443957,-71.0887858,17z/data=!3m2!4b1!5s0x89e37055dbf39f5b:0xa6234533d0ea82ad!4m5!3m4!1s0x89e37a1a6d6f7fd5:0xbd63a63c0b659388!8m2!3d42.3443957!4d-71.0865971?hl=en").toURI());
          
           }       else if(apt.equals("Greenhouse")){
               
                 Desktop.getDesktop().browse(new URL( "https://www.google.com/maps/place/The+Greenhouse+Apartments/@42.3446152,-71.0843947,17z/data=!3m1!4b1!4m5!3m4!1s0x89e37a11b08c434f:0x800b80accd9e152b!8m2!3d42.3446152!4d-71.082206?hl=en").toURI());
            

          
           } else{
              
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
            
        }
    }//GEN-LAST:event_btnlocationActionPerformed

    private void btnbooktourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbooktourActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        try {
            Connection con=SQLconnection.dbconnector();
             Statement stmt=con.createStatement();
           String Query= "INSERT INTO ApartmentBooking (ApartmentName,ApartmentType,Price,LandlordName,ApartmentID) values ('"+txtaptname.getText()+"','"+txtapttype.getText()+"','"+txtprice.getText()+"','"+txtlandname.getText()+"','"+txtid.getText()+"')"; 
        //JOptionPane.showMessageDialog(this,"Request sent Successfully");
        stmt.executeUpdate(Query);
        stmt.close();
        con.close();
        
        } catch (SQLException ex) {
            Logger.getLogger(StudentDetailsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
          int selectedRowIndex = tblapartmentlistings.getSelectedRow();
           String query = cmbtime.getSelectedItem().toString();
        if(query == "Select" ){
            JOptionPane.showMessageDialog(this, "Please Select Time Slot");
        }else if(selectedRowIndex < 0){
             JOptionPane.showMessageDialog(this, "Please Select the Apartment");
     
        
            
        } else {
          StudentDetailsPage frame=new StudentDetailsPage();
                frame.setTitle("Student Details Page");
                frame.setVisible(true);

                frame.setDefaultCloseOperation(StudentDetailsPage.EXIT_ON_CLOSE);
                frame.setResizable(false);
          }
        
    }//GEN-LAST:event_btnbooktourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbooktour;
    private javax.swing.JButton btnlocation;
    private javax.swing.JRadioButton btnonebhk;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsearch;
    private javax.swing.JRadioButton btnstudio;
    private javax.swing.JRadioButton btnthreebhk;
    private javax.swing.JRadioButton btntwobhk;
    private javax.swing.JButton btnview;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox<String> cmbtime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblaptname;
    private javax.swing.JLabel lblapttype;
    private javax.swing.JLabel lblbrokername;
    private javax.swing.JLabel lblemailid;
    private javax.swing.JLabel lblgrocery;
    private javax.swing.JLabel lblhospitals;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbllandname;
    private javax.swing.JLabel lblmbta;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblutilities;
    private javax.swing.JTable tblapartmentlistings;
    private javax.swing.JTextField txtaptname;
    private javax.swing.JTextField txtapttype;
    private javax.swing.JTextField txtbrokername;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtgrocery;
    private javax.swing.JTextField txthospitals;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlandname;
    private javax.swing.JTextField txtmbta;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtutilities;
    // End of variables declaration//GEN-END:variables
private void PopulateTable()
    {
      
  
        DefaultTableModel model=(DefaultTableModel) tblapartmentlistings.getModel();
 
        model.setRowCount(0);
        for(Apartmentlistings a: ad.getList())
        {
             Object[] row=new Object[13];
             row[0]=a.getApartmenttype();
             
             row[1]=a.getLandlordname();
             row[2]=a.getPrice();
             row[3]=a.getUtilities();
             row[4]=a.getGrocerystores();
             row[5]=a.getHospital();
             row[6]=a.getMBTA();
             row[7]=a.getBrokerName();
             row[8]=a.getEmailID();
             row[9]=a.getApartmentname();
             row[10]= a.getID();
             row[11]=a;
             
    
             model.addRow(row);
             
        }  
    }
 public void search(String str,int i) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    System.out.println(str);
        DefaultTableModel model = (DefaultTableModel) tblapartmentlistings.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        tblapartmentlistings.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str,i));
        
    }
}
